### PR TITLE
Upstream PR-6264 updates

### PR DESCRIPTION
**Pull request by plskeggs**
This PR cherry-picks the upstream PR 6264 from Hannes Tschofenig that replaces his previous PR 5061.

### CODE REVIEW

**Comment by plskeggs** [comment]
@frkv @Vge0rge @joerchan @sigvartmh please review.

**Comment by joerchan** [comment]
@plskeggs Please clarify: 

> My PR is stacked on top of my previous PR https://github.com/nrfconnect/sdk-mbedtls/pull/7; once the other is merged, I will rebase this PR to remove the associated commit.

Is this done?

Your commit is `nrf noup` and referencing that it is cherry-picked from multiple commits.
Please don't squash the commits, and if the cherry-picked commit is not merged upstream yet then the correct tag is "nrf fromlist". Please include a reference to the upstream pull-request in the commit message in that case.
If they have been merged used "nrf fromtree" and cherry-pick with -x for the "cherry-picked from <commit>" line.

**Comment by plskeggs** [comment]
@joerchan -- I replaced my squashed commit with all of his (except 2 empty ones), and one of mine to get it to build on our version of Mbed-TLS.

I added a Jira ticket to the commit messages, changed to [from list], and referenced the upstream PR.

Note that this builds on an earlier PR that Frank incorporated for me, for which he told me to use [nrf noup].  This is why I used it again.  See https://projecttools.nordicsemi.no/jira/browse/NCSDK-15193 and associated PR.

**Comment by plskeggs** [comment]
@frkv @Vge0rge @joerchan @sigvartmh -- I will be on vacation and off grid most of the time between August 20 and August 29.

If you have any input on this PR, it would be helpful to have it by tomorrow morning.

**Comment by joerchan** [comment]
> Note that this builds on an earlier PR that Frank incorporated for me, for which he told me to use [nrf noup]. This is why I used it again.

The [nrf <tag>] exists so that we can easily trace where patches in our fork of the upstream repository comes from.

NOUP: A commit that only exists in our fork of the repository and will not be sent to upstream.
FROMLIST: A commit that is backported from an upstream open PR.
FROMTREE: A commit that is backported from the upstream.

We use this when synchronizing the repositories, so that we know which action to take on each of the commits.

Your last commit does not have an nrf tag. If it is a patch you have applied yourself then please use the appropriate tag on it.

**Comment by plskeggs** [comment]
> > Note that this builds on an earlier PR that Frank incorporated for me, for which he told me to use [nrf noup]. This is why I used it again.
> 
> The [nrf ] exists so that we can easily trace where patches in our fork of the upstream repository comes from.
> 
> NOUP: A commit that only exists in our fork of the repository and will not be sent to upstream. FROMLIST: A commit that is backported from an upstream open PR. FROMTREE: A commit that is backported from the upstream.
> 
> We use this when synchronizing the repositories, so that we know which action to take on each of the commits.
> 
> Your last commit does not have an nrf tag. If it is a patch you have applied yourself then please use the appropriate tag on it.

OK, sorry about the missing tag on my last commit.  I've updated it now.

**Review by joerchan — APPROVED** [review]

**Comment by plskeggs** [comment]
I've switched this PR to use the single commit in the upstream PR 6264 rather than the author's earlier PR 5061.

**Comment by joerchan** [comment]
Can you please put the link to the upstream PR in the commit message?

**Comment by plskeggs** [comment]
> Can you please put the link to the upstream PR in the commit message?

done

**Comment by Vge0rge** [comment]
Hey, sorry for the late reply. There is a comment in the upstream PR which says that it breaks TLS1.3 configurations. I suspect that this commit will change because of this. If it is not very urgent I would prefer to wait until the update it before we merge. If this is a big inconvenience for you @plskeggs we can consider merging it soon.

**Comment by plskeggs** [comment]
The modem team pointed out a particular bug that has been fixed:  https://github.com/Mbed-TLS/mbedtls/pull/5915/files.  Perhaps we could simply add this fix for now until TLS 1.3 problems are resolved.

**Comment by Vge0rge** [comment]
> The modem team pointed out a particular bug that has been fixed: https://github.com/Mbed-TLS/mbedtls/pull/5915/files. Perhaps we could simply add this fix for now until TLS 1.3 problems are resolved.

https://github.com/nrfconnect/sdk-mbedtls/pull/11
@plskeggs   please check if this is what you need and approve this.

**Comment by frkv** [comment]
There will be a meeting on this the content of this PR. It is not cleared for addition in sdk-mbedtls at this point

**Review by frkv — APPROVED** [review]
LGTM but needs sdk-nrf manifest PR, which I will create

**Comment by plskeggs** [comment]
@frkv @joerchan @Vge0rge -- now that ARM has merged the upstream PR, what is the next step?

Is this PR needed still, or is someone at Nordic working now on updating sdk-mbedtls to the upstream version?

Although, the upstream PR was against `development`, not against Mbed-TLS 3.1.0 as I thought Nordic requested.  I also do not see any backport PRs of this feature to older versions.  So perhaps ARM is not done yet with our CID request?

**Comment by frkv** [comment]
> @frkv @joerchan @Vge0rge -- now that ARM has merged the upstream PR, what is the next step?
> 
> Is this PR needed still, or is someone at Nordic working now on updating sdk-mbedtls to the upstream version?
> 
> Although, the upstream PR was against `development`, not against Mbed-TLS 3.1.0 as I thought Nordic requested. I also do not see any backport PRs of this feature to older versions. So perhaps ARM is not done yet with our CID request?

We have to check for the ability to cherry-pick the merged commit on top of Mbed TLS v3.1.0, I think (but after main is unfrozen)

**Pull request closed without merging**
